spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-sevrice
              uri: lb://user
              predicates:
                - Path=/api/v1/users/**

            - id: calendar-service
              uri: lb://calendar
              predicates:
                - Path=/api/v1/calendars/**

server:
  port: 8222

management:
  tracing:
    sampling:
      probability: 1.0