spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user
              uri: lb://user
              predicates:
                - Path=/api/v1/users/**

            - id: auth
              uri: lb://user
              predicates:
                - Path=/api/v1/auth/**

            - id: calendar
              uri: lb://calendar
              predicates:
                - Path=/api/v1/calendars/**

            - id: calendar-invite
              uri: lb://calendar
              predicates:
                - Path=/api/v1/invites/**

            - id: calendar-member
              uri: lb://calendar
              predicates:
                - Path=/api/v1/members/**


server:
  port: 8222

management:
  tracing:
    sampling:
      probability: 1.0

