spring:
  application:
    name: calendar
  config:
    import: optional:configserver:localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/collabri_calendars
    username: postgres
    password: safwene17
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: update

server:
  port: 8070
