server:
  port: 8040
spring:
  application:
    name: notification
  config:
    import: optional:configserver:http://localhost:8888
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}  # Override via environment variable
    password: ${MAIL_PASSWORD}  # Override via environment variable
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          connection-timeout: 5000
          timeout: 3000
          write-timeout: 5000
  data:
    mongodb:
      username: ${MONGO_USERNAME}  # Override via environment variable
      password: ${MONGO_PASSWORD}
      host: localhost
      port: 27017
      database: ${MONGO_DB}  # Override via environment variable
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: CalendarGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping:
          CalendarInviteEvent:org.example.notificationservice.kafka.calendar.CalendarInviteEvent,
          EventCreatedEvent:org.example.notificationservice.kafka.calendar.EventCreatedEvent,
          TaskCreatedEvent:org.example.notificationservice.kafka.calendar.TaskCreatedEvent,
          MemberJoinedEvent:org.example.notificationservice.kafka.calendar.MemberJoinedEvent,
          MemberLeftEvent:org.example.notificationservice.kafka.calendar.MemberLeftEvent



app:
  frontend:
    invite-base: http://localhost:5173/invite   # used to build accept/decline links
  email:
    send-retry-count: 3
  jwt:
    secret: ${JWT_SECRET}  # Override via environment variable

